package Server;

import java.util.List;

import logic.Account;

/**
 * BiteMe
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class AccountApiService{
    /**
     * Create Account
     *
     * This can only be done by the logged in Account.
     *
     */
    public static void createAccount(Account body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Creates list of Accounts with given input array
     *
     */
    public static void createAccountsWithArrayInput(List<Account> body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Creates list of Accounts with given input array
     *
     */
    public void createAccountsWithListInput(List<Account> body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Delete Account
     *
     * This can only be done by the logged in Account.
     *
     */
    public static void deleteAccount(String userName) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Get Account by Account name
     *
     */
    public static Account getAccountByName(String userName) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Logs Account into the system
     *
     */
    public static String loginAccount(String userName, String password) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Logs out current logged in Account session
     *
     */
    public static void logoutAccount() {
        // TODO: Implement...
        
        
    }
    
    /**
     * Updated Account
     *
     * This can only be done by the logged in Account.
     *
     */
    public static void updateAccount(Account body, String userName) {
        // TODO: Implement...
        
        
    }
    
}

