package Server;
import java.util.List;

import logic.Restaurant;


/**
 * BiteMe
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class BranchManagerApiService{
    /**
     * Get all the reports for the branch
     *
     * This can only be done by the logged in branch manager.
     *
     */
    public static void getBranchOrders() {
        // TODO: Implement...

    }
    
    /**
     * Get the reports for the branch
     *
     * This can only be done by the logged in branch manager.
     *
     */
    public static void getBranchReports(List<String> reportType) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Register a resturant - mind that the supplier shcema isn&#x27;t finish
     *
     * This can only be done by the logged in branch manager.
     *
     */
    public static void registerSupplier(Restaurant body) {
        // TODO: Implement...
        
        
    } 
}

