package Server;

import java.util.List;

import logic.BusinessAccount;
import logic.Employer;


/**
 * BiteMe
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class HrApiService{
    /**
     * Approve business account
     *
     */
    public void approveBusinessAccount(String userName) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Get all business acccounts that has isApproved &#x3D; &#x27;false&#x27;
     *
     */
    public List<BusinessAccount> getAllUnapprovedBusinessAccount(Long branchManagerID) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Register new Buisness
     *
     */
    public void registerBusiness(Employer body) {
        // TODO: Implement...
        
        
    }
    
}

