package Server;


/**
 * BiteMe
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class OrderApiService{
    /**
     * Add a new order
     *
     */
    public static void addOrder(Order body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Return all the orders
     *
     */
    public static List<Order> allOrders(String resturantID) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Deletes an order
     *
     */
    public static void deleteOrder(Long orderId) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Find order by ID
     *
     * Returns a single order
     *
     */
    public static Order getOrderById(Long orderId) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Get payment approval for monthly budget
     *
     */
    public static void getPaymentApproval(Long accountID) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Get resturants for the specific
     *
     */
    public static List<Resturant> getResturants(List<String> area) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Updates a order in the DB with form data
     *
     */
    public static void updateOrderWithForm(OrdersGetOrderByIdBody body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Updates a order in the DB with form data
     *
     */
    public static void updateOrderWithForm(Long orderId, String address, String delivery) {
        // TODO: Implement...
        
        
    }
    
}

