package Server;

import java.util.List;

import logic.*;
/**
 * BiteMe
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class OrderApiService{
    /**
     * Add a new order
     *
     */
    public static void addOrder(Order body, Response response) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Return all the orders
     *
     */
    public static List<Order> allOrders(String resturantID, Response response) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Deletes an order
     *
     */
    public static void deleteOrder(Integer orderId, Response response) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Find order by ID
     *
     * Returns a single order
     *
     */
    public static Order getOrderById(Integer orderId, Response response) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Get payment approval for monthly budget
     *
     */
    public static void getPaymentApproval(Integer accountID, Response response) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Get resturants for the specific
     *
     */
    public static List<Supplier> getResturants(String area, Response response) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Updates a order in the DB with form data
     *
     */
    public static void updateOrderWithForm(Order body, Response response) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Updates a order in the DB with form data
     *
     */
    public static void updateOrderWithForm(Long orderId, String address, String delivery, Response response) {
        // TODO: Implement...
        
        
    }
    
}

