package Server;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;

import logic.Category;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.mysql.cj.Query;

import common.MyPhoto;
import logic.Item;
import logic.Menu;
import logic.MyFile;
import logic.Options;
import logic.Restaurant;

/**
 * BiteMe
 *
 * <p>
 * No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 */
public class RestaurantApiService {
    
    /**
     * Get approved restaurants for the specific location
     *
     */
    @SuppressWarnings("resource")
	public static void getRestaurants(String area, Response response, String type) {
    		PreparedStatement stmt;
    		ArrayList<Restaurant> restaurants = new ArrayList<>();
    		ArrayList<MyPhoto> photos = new ArrayList<>();
    		Restaurant restaurant = null;
    		try {
    			stmt = EchoServer.con.prepareStatement("SELECT * FROM restaurant biteme.restaurant WHERE restaurant.IsApproved = 1" +area
    					+ type + ";");
    			ResultSet rs = stmt.executeQuery();
    			while (rs.next()) {
    				restaurant = new Restaurant(rs.getInt(QueryConsts.RESTAURANT_ID), rs.getBoolean(QueryConsts.RESTAURANT_IS_APPROVED),
    						rs.getInt(QueryConsts.RESTAURANT_BRANCH_MANAGER_ID), rs.getString(QueryConsts.RESTAURANT_NAME),
    						rs.getString(QueryConsts.RESTAURANT_AREA), rs.getString(QueryConsts.RESTAURANT_TYPE),
    						rs.getInt(QueryConsts.RESTAURANT_USER_ID), rs.getString(QueryConsts.RESTAURANT_PHOTO));
    				restaurants.add(restaurant);
    				MyPhoto msg= new MyPhoto(Integer.toString(restaurant.getID())); //"diagnosisE.jpg"
    				String path = QueryConsts.LocalfilePath + Integer.toString(restaurant.getID());
    				  try{
    					      File newFile = new File (path);		      		      
    					      byte [] mybytearray  = new byte [(int)newFile.length()];
    					      FileInputStream fis = new FileInputStream(newFile);
    					      BufferedInputStream bis = new BufferedInputStream(fis);			    					      
    					      msg.initArray(mybytearray.length);
    					      msg.setSize(mybytearray.length);  					      
    					      bis.read(msg.getMybytearray(),0,mybytearray.length);
    					    }
    					catch (Exception e) {
    						System.out.println("Error send (Files)msg) to Server");
    					}
    				  photos.add(msg);
    			}
    		} catch (SQLException e) {
    			e.printStackTrace();
    		}
    		response.setCode(200);
    		response.setDescription("Success in fetching orders");
    		Gson gson = new Gson();
    		JsonElement v = gson.toJsonTree(restaurants);
    		JsonElement pics = gson.toJsonTree(photos);
    		JsonElement j = gson.toJsonTree(new Object());
    		j.getAsJsonObject().add("restaurants", v);
    		j.getAsJsonObject().add("image",pics);
    		response.setBody(gson.toJson(j));
    }
    
    public static void getAllRestaurants(String area, Response response, String type) {
    	getRestaurants("and restaurant.Area = " +area, response, "");
    }
    
    /**
     * Get restaurants for the specific location
     *
     */
    public static void getRestaurantsByType(String area, String type, Response response) {
    	getRestaurants("and restaurant.Area = " +area, response, "and restaurant.Type = " +type);
    }
    /**
     * Get all categories
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void getAllCategories(int restaurantID, Response response) {
    	PreparedStatement stmt;
		ArrayList<Category> categories = new ArrayList<>();
		HashMap<String, ArrayList<String>> cat = new HashMap<>();
		Category category = null;
		try {
			stmt = EchoServer.con.prepareStatement("SELECT DISTINCT (items.category, items.subCategory) FROM items biteme.item"
					+ " WHERE items.restaurantNID = ?;");
			stmt.setInt(1, restaurantID);
			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				if(cat.containsKey(rs.getString(1))) {
					cat.get(rs.getString(1)).add(rs.getString(2));
				}
				else {
					ArrayList<String> newCategory = new ArrayList<>();
					newCategory.add(rs.getString(2));
					cat.put(rs.getString(1), newCategory);
				}
			}
			for (String category2 : cat.keySet()) {
				category = new Category(category2);
				
				for (String category3 : cat.get(category2)) {
					category.getSubCategory().add(category3);
				}
				categories.add(category);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		response.setCode(200);
		response.setDescription("Success in fetching categories for restaurantID" + Integer.toString(restaurantID));
		response.setBody(categories.toArray());        
    }
	/**
     * Getting list of all related items
     *
     * This can only be done by the logged in supplier.
     *
     */
	public static void allCategoryItems(String menuName, String itemCategory, Long resturantID, Response response) {
        // TODO: Implement...
        
    }
	/**
     * Getting list of all related items
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void allSubCategoryItems(String menuName, String itemCategory, String itemSubCategory, Long resturantID) {
        // TODO: Implement...
        
    }
	/**
	 * Getting list of all related items
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void allItems(String menuName, int restaurantID, Response response) {
		PreparedStatement stmt;
		ArrayList<Item> items = new ArrayList<>();
		ArrayList<Options> options = new ArrayList<>();
		Item item = null;
		try {
			stmt = EchoServer.con.prepareStatement("SELECT * FROM items biteme.item, itemInMenu biteme.item_in_menu"
					+ " WHERE items.RestaurantID = ? and itemInMenu.ItemID = items.ItemID and"
					+ "itemInMenu.RestaurantID = ? and itemInMenu.MenuName = ?;");
			stmt.setInt(1, restaurantID);
			stmt.setInt(2, restaurantID);
			stmt.setString(3, menuName);
			stmt.executeQuery();
			ResultSet rs = stmt.getResultSet();
			while (rs.next()) {
				item = new Item(rs.getString(QueryConsts.ITEM_CATEGORY), rs.getString(QueryConsts.ITEM_SUB_CATEGORY), rs.getInt(QueryConsts.ITEM_ID), 
						rs.getInt(QueryConsts.ITEM_RES_ID),rs.getString(QueryConsts.ITEM_NAME), rs.getFloat(QueryConsts.ITEM_PRICE), 
						rs.getString(QueryConsts.ITEM_DESCRIPTION),rs.getString(QueryConsts.ITEM_INGRIDIENTS), null, rs.getString(QueryConsts.ITEM_IMAGE),
						rs.getInt(QueryConsts.ITEM_AMOUNT));
				stmt = EchoServer.con.prepareStatement("SELECT * FROM options biteme.optional_category WHERE options.itemID = ?;");
				stmt.setInt(1, item.getItemID());
				stmt.executeQuery();
				ResultSet rs2 = stmt.getResultSet();
				while(rs2.next()) {
					options.add(new Options(rs2.getString(QueryConsts.OPTIONAL_TYPE), rs2.getString(QueryConsts.OPTIONAL_SPECIFY), rs2.getInt(QueryConsts.OPTIONAL_ITEM_ID)));
				}
				item.setOptions((Options[])options.toArray());
				options.clear();
				items.add(item);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		response.setCode(200);
		response.setDescription("Success in fetching categories for restaurantID" + Integer.toString(restaurantID));
		response.setBody(categories.toArray()); 
	}

	/**
	 * Get all menus
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void allMenues(int restaurantID, Response response) {
		ResultSet rs1, rs2, rs3;
		ArrayList<Menu> menus = new ArrayList<>();
		ArrayList<Item> items = new ArrayList<>();
		ArrayList<Options> options = new ArrayList<>();
		Menu mtemp;
		Item itemp;
		Options otemp;

		try {
			PreparedStatement getMenus = EchoServer.con
					.prepareStatement("SELECT * FROM biteme.menu WHERE RestaurantID = ?");
			getMenus.setInt(1, restaurantID);
			getMenus.execute();
			rs1 = getMenus.getResultSet();

			while (rs1.next()) {
				mtemp = new Menu(rs1.getString(2), restaurantID);

				PreparedStatement getItems = EchoServer.con
						.prepareStatement("SELECT I.* FROM biteme.item_in_menu IIM, biteme.item I WHERE "
								+ "IIM.RestaurantID = ? AND IIM.MenuName = ? AND IIM.ItemID = I.ItemID"
								+ "AND IIM.RestaurantID = I.RestaurantID");
				getItems.setInt(1, restaurantID);
				getItems.setString(2, mtemp.getName());
				getItems.execute();
				rs2 = getItems.getResultSet();

				while (rs2.next()) {
	
					itemp = new Item(rs2.getString(QueryConsts.ITEM_CATEGORY), rs2.getString(QueryConsts.ITEM_SUB_CATEGORY),rs2.getInt(QueryConsts.ITEM_ID),
							rs2.getInt(QueryConsts.ITEM_RES_ID),rs2.getString(QueryConsts.ITEM_NAME), rs2.getFloat(QueryConsts.ITEM_PRICE),
							rs2.getString(QueryConsts.ITEM_DESCRIPTION), rs2.getString(QueryConsts.ITEM_INGRIDIENTS), null,
							rs2.getString(QueryConsts.ITEM_IMAGE), rs2.getInt(QueryConsts.ITEM_AMOUNT));

					// get optional for each item

					PreparedStatement getOptions = EchoServer.con
							.prepareStatement("SELECT * FROM biteme.optional_category WHERE itemID = ?");
					getOptions.setInt(1, itemp.getItemID());
					getOptions.execute();
					rs3 = getOptions.getResultSet();

					while (rs3.next()) {
						otemp = new Options(rs3.getString(QueryConsts.OPTIONAL_TYPE), rs3.getString(QueryConsts.OPTIONAL_SPECIFY),
								itemp.getItemID());

						options.add(otemp);
					}

					// from ArrayList<T> to T[]

					itemp.setOptions(options.toArray(new Options[0]));

					items.add(itemp);
					
					options.clear();
				}
				mtemp.setItems(items.toArray(new Item[0]));
				
				menus.add(mtemp);
			
			}

		} catch (SQLException e) {
			response.setCode(405);
			response.setDescription("Invalid input");
			return;
		}

//		// if we don't have menus
//
//		if (menus.size() == 0)
//			return;
//
//		// get for each menu the items
//
//		for (Menu menu : menus) {
//			try {
//				PreparedStatement getItems = EchoServer.con
//						.prepareStatement("SELECT I.* FROM biteme.item_in_menu IIM, biteme.item I WHERE "
//								+ "IIM.RestaurantID = ? AND IIM.MenuName = ? AND IIM.ItemID = I.ItemID"
//								+ "AND IIM.RestaurantID = I.RestaurantID");
//				getItems.setInt(1, restaurantID);
//				getItems.setString(2, menu.getName());
//				getItems.execute();
//				rs1 = getItems.getResultSet();
//
//				while (rs1.next()) {
//					itemp = new Item(rs1.getInt(QueryConsts.ITEM_ID), restaurantID, rs1.getString(QueryConsts.ITEM_TYPE),
//							rs1.getString(QueryConsts.ITEM_NAME), rs1.getFloat(QueryConsts.ITEM_PRICE),
//							rs1.getString(QueryConsts.ITEM_DESCRIPTION), rs1.getString(QueryConsts.ITEM_INGRIDIENTS), null,
//							rs1.getBytes(QueryConsts.ITEM_IMAGE));
//
//					// get optional for each item
//
//					PreparedStatement getOptions = EchoServer.con
//							.prepareStatement("SELECT * FROM biteme.optional_category WHERE itemID = ?");
//					getOptions.setInt(1, itemp.getItemID());
//					getOptions.execute();
//					rs2 = getOptions.getResultSet();
//
//					while (rs2.next()) {
//						otemp = new Options(rs2.getString(QueryConsts.OPTIONAL_TYPE), rs2.getString(QueryConsts.OPTIONAL_SPECIFY),
//								itemp.getItemID());
//
//						options.add(otemp);
//					}
//
//					// from ArrayList<T> to T[]
//
//					itemp.setOptions(options.toArray(new Options[0]));
//
//					items.add(itemp);
//				}
//
//			} catch (SQLException e) {
////			response.setCode(405);
////			response.setDescription("Invalid input");
//				return;
//			}
//		}

	}

	/**
	 * Approve order
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void approveOrder(Long orderId) {
		// TODO: Implement...

	}

	/**
	 * Create item
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void createItem(Item body) {
		// TODO: Implement...

	}

	/**
	 * Create menu
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void createMenu(NewMenu body) {
		// TODO: Implement...

	}

	/**
	 * Edit menu
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void editMenu(NewMenu body) {
		// TODO: Implement...

	}

	/**
	 * Delete item
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void suppliersItemsDelete(String itemName) {
		// TODO: Implement...

	}

}
