package Server;

import java.util.List;

import javax.ws.rs.*;

import org.apache.cxf.jaxrs.ext.multipart.*;


/**
 * BiteMe
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class SupplierApiService{
    /**
     * Getting list of all related items
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static List<ItemInMenu> allItems(String menuName, Long resturantID) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Get all menus
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static Menu allMenues() {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * Approve order
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void approveOrder(Long orderId) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Create item
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void createItem(Item body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Create menu
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void createMenu(NewMenu body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Edit menu
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void editMenu(NewMenu body) {
        // TODO: Implement...
        
        
    }
    
    /**
     * Delete item
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void suppliersItemsDelete(String itemName) {
        // TODO: Implement...
        
        
    }
    
}

