package biteme.server;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import logic.Category;
import logic.Item;
import logic.Menu;
import logic.Options;
import logic.Restaurant; 

/**
 * BiteMe
 *
 * <p>
 * No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 */
public class RestaurantApiService {
    
    /**
     * Get approved restaurants for the specific location
     *
     */
    @SuppressWarnings("resource")
	public static void getRestaurants(String area, Response response, String type) {
    		PreparedStatement stmt;
    		ArrayList<Restaurant> restaurants = new ArrayList<>();
    		Restaurant restaurant = null;
    		try {
    			stmt = EchoServer.con.prepareStatement("SELECT * FROM restaurant biteme.restaurant WHERE restaurant.IsApproved = 1" +area
    					+ type + ";");
    			ResultSet rs = stmt.executeQuery();
    			while (rs.next()) {
    				restaurant = new Restaurant(rs.getInt(QueryConsts.RESTAURANT_ID),rs.getBoolean(QueryConsts.RESTAURANT_IS_APPROVED), rs.getInt(QueryConsts.RESTAURANT_BRANCH_MANAGER_ID),
							rs.getString(QueryConsts.RESTAURANT_NAME), rs.getString(QueryConsts.RESTAURANT_AREA),rs.getString(QueryConsts.RESTAURANT_TYPE),
							rs.getString(QueryConsts.RESTAURANT_USER_NAME),rs.getString(QueryConsts.RESTAURANT_PHOTO), rs.getString(QueryConsts.RESTAURANT_ADDRESS),
							rs.getString(QueryConsts.RESTAURANT_DESCRIPTION));
    				restaurants.add(restaurant);
    			}
    		} catch (SQLException e) {
    			e.printStackTrace();
    		}
    		response.setCode(200);
    		response.setDescription("Success in fetching restaurants");
    		response.setBody(restaurants);
    }
    
    public static void getAllRestaurants(String area, Response response) {
    	getRestaurants("and restaurant.Area = " +area, response, "");
    }
    
    /**
     * Get restaurants for the specific location
     *
     */
    public static void getRestaurantsByType(String area, String type, Response response) {
    	getRestaurants("and restaurant.Area = " +area, response, "and restaurant.Type = " +type);
    }
    /**
     * Get all categories
     *
     * This can only be done by the logged in supplier.
     *
     */
    public static void getAllCategories(int restaurantID, Response response) {
    	PreparedStatement stmt;
		ArrayList<Category> categories = new ArrayList<>();
		HashMap<String, ArrayList<String>> cat = new HashMap<>();
		Category category = null;
		try {
			stmt = EchoServer.con.prepareStatement("SELECT DISTINCT (items.category, items.subCategory) FROM items biteme.item"
					+ " WHERE items.restaurantNID = ?;");
			stmt.setInt(1, restaurantID);
			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				if(cat.containsKey(rs.getString(1))) {
					cat.get(rs.getString(1)).add(rs.getString(2));
				}
				else {
					ArrayList<String> newCategory = new ArrayList<>();
					newCategory.add(rs.getString(2));
					cat.put(rs.getString(1), newCategory);
				}
			}
			for (String category2 : cat.keySet()) {
				category = new Category(category2, new ArrayList<String>);
				
				for (String category3 : cat.get(category2)) {
					category.getSubCategory().add(category3);
				}
				categories.add(category);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		response.setCode(200);
		response.setDescription("Success in fetching categories for restaurantID" + Integer.toString(restaurantID));
		response.setBody(categories.toArray());        
    }
	/**
	 * Getting list of all related items
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void allItems(int restaurantID, Response response) {
		PreparedStatement stmt;
		ArrayList<Item> items = new ArrayList<>();
		ArrayList<Options> options = new ArrayList<>();
		Item item = null;
		try {
			stmt = EchoServer.con.prepareStatement("SELECT * FROM items biteme.item, itemInMenu biteme.item_in_menu"
					+ " WHERE items.RestaurantID = ? and itemInMenu.ItemID = items.ItemID and"
					+ "itemInMenu.RestaurantID = ?;");
			stmt.setInt(1, restaurantID);
			stmt.setInt(2, restaurantID);
			stmt.executeQuery();
			ResultSet rs = stmt.getResultSet();
			while (rs.next()) {
				item = new Item(rs.getString(QueryConsts.ITEM_CATEGORY), rs.getString(QueryConsts.ITEM_SUB_CATEGORY), rs.getInt(QueryConsts.ITEM_ID), 
						rs.getInt(QueryConsts.ITEM_RES_ID),rs.getString(QueryConsts.ITEM_NAME), rs.getFloat(QueryConsts.ITEM_PRICE), 
						rs.getString(QueryConsts.ITEM_DESCRIPTION),rs.getString(QueryConsts.ITEM_INGREDIENTS), null, rs.getString(QueryConsts.ITEM_IMAGE),
						0);
				stmt = EchoServer.con.prepareStatement("SELECT * FROM options biteme.optional_category WHERE options.itemID = ?;");
				stmt.setInt(1, item.getItemID());
				stmt.executeQuery();
				ResultSet rs2 = stmt.getResultSet();
				while(rs2.next()) {
					options.add(new Options(rs2.getString(QueryConsts.OPTIONAL_TYPE), rs2.getString(QueryConsts.OPTIONAL_SPECIFY), rs2.getInt(QueryConsts.OPTIONAL_ITEM_ID)));
				}
				item.setOptions((Options[])options.toArray());
				options.clear();
				items.add(item);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		response.setCode(200);
		response.setDescription("Success in fetching all restaurant itesm" + Integer.toString(restaurantID));
		response.setBody(items.toArray()); 
	}

	/**
	 * Get all menus
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void allMenues(int restaurantID, Response response) {
		ResultSet rs1, rs2, rs3;
		ArrayList<Menu> menus = new ArrayList<>();
		ArrayList<Item> items = new ArrayList<>();
		ArrayList<Options> options = new ArrayList<>();
		Menu mtemp;
		Item itemp;
		Options otemp;

		try {
			PreparedStatement getMenus = EchoServer.con
					.prepareStatement("SELECT * FROM biteme.menu WHERE RestaurantID = ?");
			getMenus.setInt(1, restaurantID);
			getMenus.execute();
			rs1 = getMenus.getResultSet();

			while (rs1.next()) {
				mtemp = new Menu(rs1.getString(2), restaurantID);

				PreparedStatement getItems = EchoServer.con
						.prepareStatement("SELECT I.* FROM biteme.item_in_menu IIM, biteme.item I WHERE "
								+ "IIM.RestaurantID = ? AND IIM.MenuName = ? AND IIM.ItemID = I.ItemID"
								+ "AND IIM.RestaurantID = I.RestaurantID");
				getItems.setInt(1, restaurantID);
				getItems.setString(2, mtemp.getName());
				getItems.execute();
				rs2 = getItems.getResultSet();

				while (rs2.next()) {
	
					itemp = new Item(rs2.getString(QueryConsts.ITEM_CATEGORY), rs2.getString(QueryConsts.ITEM_SUB_CATEGORY),rs2.getInt(QueryConsts.ITEM_ID),
							rs2.getInt(QueryConsts.ITEM_RES_ID),rs2.getString(QueryConsts.ITEM_NAME), rs2.getFloat(QueryConsts.ITEM_PRICE),
							rs2.getString(QueryConsts.ITEM_DESCRIPTION), rs2.getString(QueryConsts.ITEM_INGREDIENTS), null,
							rs2.getString(QueryConsts.ITEM_IMAGE), 0);

					// get optional for each item

					PreparedStatement getOptions = EchoServer.con
							.prepareStatement("SELECT * FROM biteme.optional_category WHERE itemID = ?");
					getOptions.setInt(1, itemp.getItemID());
					getOptions.execute();
					rs3 = getOptions.getResultSet();

					while (rs3.next()) {
						otemp = new Options(rs3.getString(QueryConsts.OPTIONAL_TYPE), rs3.getString(QueryConsts.OPTIONAL_SPECIFY),
								itemp.getItemID());

						options.add(otemp);
					}

					// from ArrayList<T> to T[]

					itemp.setOptions(options.toArray(new Options[0]));

					items.add(itemp);
					
					options.clear();
				}
				mtemp.setItems(items.toArray(new Item[0]));
				
				menus.add(mtemp);
			
			}

		} catch (SQLException e) {
			response.setCode(405);
			response.setDescription("Invalid input");
			return;
		}

//		// if we don't have menus
//
//		if (menus.size() == 0)
//			return;
//
//		// get for each menu the items
//
//		for (Menu menu : menus) {
//			try {
//				PreparedStatement getItems = EchoServer.con
//						.prepareStatement("SELECT I.* FROM biteme.item_in_menu IIM, biteme.item I WHERE "
//								+ "IIM.RestaurantID = ? AND IIM.MenuName = ? AND IIM.ItemID = I.ItemID"
//								+ "AND IIM.RestaurantID = I.RestaurantID");
//				getItems.setInt(1, restaurantID);
//				getItems.setString(2, menu.getName());
//				getItems.execute();
//				rs1 = getItems.getResultSet();
//
//				while (rs1.next()) {
//					itemp = new Item(rs1.getInt(QueryConsts.ITEM_ID), restaurantID, rs1.getString(QueryConsts.ITEM_TYPE),
//							rs1.getString(QueryConsts.ITEM_NAME), rs1.getFloat(QueryConsts.ITEM_PRICE),
//							rs1.getString(QueryConsts.ITEM_DESCRIPTION), rs1.getString(QueryConsts.ITEM_INGRIDIENTS), null,
//							rs1.getBytes(QueryConsts.ITEM_IMAGE));
//
//					// get optional for each item
//
//					PreparedStatement getOptions = EchoServer.con
//							.prepareStatement("SELECT * FROM biteme.optional_category WHERE itemID = ?");
//					getOptions.setInt(1, itemp.getItemID());
//					getOptions.execute();
//					rs2 = getOptions.getResultSet();
//
//					while (rs2.next()) {
//						otemp = new Options(rs2.getString(QueryConsts.OPTIONAL_TYPE), rs2.getString(QueryConsts.OPTIONAL_SPECIFY),
//								itemp.getItemID());
//
//						options.add(otemp);
//					}
//
//					// from ArrayList<T> to T[]
//
//					itemp.setOptions(options.toArray(new Options[0]));
//
//					items.add(itemp);
//				}
//
//			} catch (SQLException e) {
////			response.setCode(405);
////			response.setDescription("Invalid input");
//				return;
//			}
//		}

	}

	/**
	 * Approve order
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void approveOrder(int orderId, Response response) {
		ResultSet rs;
		try {
			PreparedStatement approveOrder = EchoServer.con
					.prepareStatement("UPDATE biteme.order AS orders SET isApproved = 1 WHERE order.OrderNum = ?;");
			approveOrder.setInt(1, orderId);
			approveOrder.execute();
			rs = approveOrder.getResultSet();
			if (rs.rowUpdated() == false) {
				throw new SQLException("couldn't approve order " + Integer.toString(orderId));
			}
			DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
			LocalDateTime now = LocalDateTime.now();
			PreparedStatement updateApprovalTime = EchoServer.con
					.prepareStatement("UPDATE biteme.order AS orders SET approved_time = ? WHERE order.OrderNum = ?;");
			updateApprovalTime.setString(1, dtf.format(now));
			updateApprovalTime.setInt(2, orderId);
			updateApprovalTime.execute();
			rs = updateApprovalTime.getResultSet();
			if (rs.rowUpdated() == false) {
				throw new SQLException("couldn't update the time in menu" + Integer.toString(orderId));
			}
		} catch (SQLException e) {
			response.setCode(400);
			response.setDescription(e.getMessage());
			response.setBody(null);
			return;
		}
		response.setCode(200);
		response.setDescription("Success in approve order " + Integer.toString(orderId));
		response.setBody(null);
		
	}

	/**
	 * Create item
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void createItem(Item item, Response response) {
		ResultSet rs;
		int orderID = 0, shipmentID, price;
		Options options = null;
		try {
			PreparedStatement postOrder = EchoServer.con.prepareStatement(
					"INSERT INTO items biteme.item (Category, SubCategory, Name, Price, ItemID, Ingredients,"
							+ "RestaurantID, Image, Description)"
							+ " VALUES (?,?,?,?,?,?,?,?,?);");
			postOrder.setString(1, item.getCategory());
			postOrder.setString(2, item.getSubcategory());
			postOrder.setString(3, item.getName());
			postOrder.setFloat(4, item.getPrice());
			postOrder.setInt(5, item.getItemID());
			postOrder.setString(6, item.getIngrediants());
			postOrder.setInt(7, item.getRestaurantID());
			postOrder.setString(8, item.getPhoto());
			postOrder.setString(9, item.getDescription());
			postOrder.execute();
			rs = postOrder.getResultSet();
		} catch (SQLException e) {
			response.setCode(405);
			response.setDescription("Invalid input");
			return;
		}

	}

	/**
	 * Create menu
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void createMenu(Menu body) {
		// TODO: Implement...

	}

	/**
	 * Edit menu
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void editMenu(Menu body) {
		// TODO: Implement...

	}

	/**
	 * Delete item
	 *
	 * This can only be done by the logged in supplier.
	 *
	 */
	public static void itemsDelete(int itemID, Response response) {
		try {
			PreparedStatement deleteItem = EchoServer.con.prepareStatement(
					"DELETE FROM items biteme.item WHERE items.ItemID = ?;");
			deleteItem.setInt(1, itemID);
			// Its the first userName that he had so the test is in users table on login
			deleteItem.execute();
			deleteItem.getResultSet();
		} catch (SQLException e) {
			response.setCode(400);
			response.setDescription("Fields are missing");
			response.setBody(null);
			return;
		}
		response.setCode(200);
		response.setDescription("Success in deleting item " + itemID);
		response.setBody(null);

	}

}
